/*
 * This source file was generated by the Gradle 'init' task
 */
package uk.org.webcompere.spc;

import com.beust.jcommander.JCommander;
import uk.org.webcompere.spc.cli.SpcArgs;

public class App {

    public static void main(String[] args) {
        SpcArgs arguments = new SpcArgs();
        JCommander cliParser = JCommander.newBuilder()
                .addObject(arguments)
                .build();

        cliParser.parse(args);

        System.out.println(arguments);
    }
}
