/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application

    // for fat jars
    id("com.github.johnrengelman.shadow") version "8.1.1"

    // y'know, for coverage
    jacoco

    id("jacoco-report-aggregation")

    // fine, let's lombok this stupid set of POJOs
    id("io.freefair.lombok") version "8.13"

    id("com.diffplug.spotless") version "7.0.3"

    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

spotless {
    java {
        palantirJavaFormat()
    }
}

dependencies {
    // https://mvnrepository.com/artifact/com.beust/jcommander
    implementation("com.beust:jcommander:1.82")

    // add in Lombok because I gave up
    compileOnly("org.projectlombok:lombok:1.18.36")
    annotationProcessor("org.projectlombok:lombok:1.18.36")
    testCompileOnly("org.projectlombok:lombok:1.18.36")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.36")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation("org.assertj:assertj-core:3.27.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.mockito:mockito-junit-jupiter:5.16.1")

    testImplementation("uk.org.webcompere:system-stubs-jupiter:2.1.7")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

application {
    // Define the main class for the application.
    mainClass = "uk.org.webcompere.spc.App"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

tasks.shadowJar {
    archiveBaseName.set("spring-properties-cleaner")
    archiveClassifier.set("")
    archiveVersion.set("1.0")
}

jacoco {
    toolVersion = "0.8.12" // Ensure you're using the latest version
}

tasks.jacocoTestReport {
    dependsOn(tasks.test) // Ensure tests run before generating reports

    reports {
        xml.required.set(true)
        html.required.set(true)
        csv.required.set(false)
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "uk.org.webcompere"
            artifactId = "spring-properties-cleaner-app"
            version = "1.0.0"

            artifact(tasks.shadowJar.get()) {
                classifier = null // Ensures it replaces the main JAR
            }
        }
    }
}