name: Build on Push
run-name: Build commit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          # Install gpg secret key
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG
      - run: ./gradlew spotlessCheck build shadowJar
      - run: bash <(curl -s https://codecov.io/bash)

