name: Build on Push
run-name: Build commit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt-openj9
          java-version: 11
          cache: maven
      - run: ./gradlew build shadowJar
      - run: bash <(curl -s https://codecov.io/bash)

